name: is3103
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.1
  firebase: ^7.1.0
  queries: ^0.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
